# Default initial positions for multirobot's ros2_control fake system

initial_positions:
  p_link1_to_link2: 0
  p_link2_to_link3: 0
  p_link3_to_link4: 0
  p_link4_to_link5: 0
  p_manip_base_to_link1: 0
  w_link1_to_link2: 0
  w_link2_to_link3: 0
  w_link3_to_link4: 0
  w_link4_to_link5: 0
  w_link5_to_link6: 0
  w_manip_base_to_link1: 0