# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    positioner_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    welder_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

positioner_planning_group_controller:
  ros__parameters:
    joints:
      - p_manip_base_to_link1
      - p_link1_to_link2
      - p_link2_to_link3
      - p_link3_to_link4
      - p_link4_to_link5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
welder_planning_group_controller:
  ros__parameters:
    joints:
      - w_manip_base_to_link1
      - w_link1_to_link2
      - w_link2_to_link3
      - w_link3_to_link4
      - w_link4_to_link5
      - w_link5_to_link6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity