# Default initial positions for welder's ros2_control fake system

initial_positions:
  link1_to_link2: 0
  link2_to_link3: 0
  link3_to_link4: 0
  link4_to_link5: 0
  link5_to_link6: 0
  manip_base_to_link1: 0