# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - welder_planning_group_controller

  welder_planning_group_controller:
    type: FollowJointTrajectory
    action_ns: welder_follow_joint_trajectory  # 修改 action_ns，避免冲突
    default: true
    joints:
      - manip_base_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_link4
      - link4_to_link5
      - link5_to_link6
