# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    controller_names:
      - positioner_planning_group_controller
      - positioner_joint_state_broadcaster

    positioner_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

positioner_planning_group_controller:
  ros__parameters:
    joints:
      - manip_base_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_link4
      - link4_to_link5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
